# Generated by Django 5.1.2 on 2025-10-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_business_free_reward_threshold_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='password',
            field=models.CharField(blank=True, help_text='Business password for in-person access', max_length=128),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, help_text='Business phone number', max_length=20),
        ),
    ]
