# Generated by Django 5.2.7 on 2025-11-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_business_password_business_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Slider image', null=True, upload_to='sliders/')),
                ('store', models.CharField(help_text='Store name', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Store address', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Slider description')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='loyalty.business')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
