# Generated by Django 5.2.7 on 2025-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_reward',
            field=models.BooleanField(default=False, help_text='If True, this is a reward item that costs points. If False, this is a menu item that gives points.'),
        ),
    ]
