# Generated by Django 5.0.7 on 2025-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_business_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='stamp_count',
            new_name='points_balance',
        ),
        migrations.RemoveField(
            model_name='business',
            name='free_reward_threshold',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='target',
        ),
        migrations.AddField(
            model_name='business',
            name='reward_point_cost',
            field=models.PositiveIntegerField(default=100, help_text='Points required for the default reward', verbose_name='Reward point cost'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='reward_point_cost',
            field=models.PositiveIntegerField(default=100, help_text='Points required to unlock the default reward for this wallet'),
        ),
    ]
