# Generated by Django 5.0.7 on 2025-11-28 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_business_email_and_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, help_text='Business contact email', max_length=254),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='loyalty.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='loyalty.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['business'], name='loyalty_fav_busines_0972f5_idx'), models.Index(fields=['customer'], name='loyalty_fav_custome_9735c6_idx')],
                'unique_together': {('customer', 'business')},
            },
        ),
    ]
