# Generated by Django 5.0.7 on 2025-12-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_alter_business_email_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='نوع مدل (مثلاً Product یا Slider)', max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID شیء در مدل اصلی')),
                ('original_path', models.CharField(help_text='مسیر اصلی فایل در storage', max_length=500)),
                ('image_data', models.TextField(blank=True, help_text='تصویر به صورت base64', null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL تصویر در storage', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='حجم فایل به بایت', null=True)),
                ('content_type_header', models.CharField(blank=True, help_text='Content-Type (مثلاً image/jpeg)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='آخرین زمان دسترسی')),
            ],
            options={
                'verbose_name': 'Image Cache',
                'verbose_name_plural': 'Image Caches',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='loyalty_ima_content_7e1d8f_idx'), models.Index(fields=['original_path'], name='loyalty_ima_origina_096821_idx')],
                'unique_together': {('content_type', 'object_id', 'original_path')},
            },
        ),
    ]
