# Generated by Django 5.0.7 on 2025-11-21 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_business_slug'),
        ('reviews', '0002_service_reviewresponse_and_review_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_status_5966f7_idx',
            old_name='reviews_re_status_aaaa3f_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_target__c8472e_idx',
            old_name='reviews_re_target__5542d3_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='loyalty.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='review',
            name='target_type',
            field=models.CharField(choices=[('business', 'Business'), ('service', 'Service'), ('product', 'Product')], default='business', max_length=12),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='reviews_rev_product_a9ee0d_idx'),
        ),
    ]
