# Generated by Django 5.0.7 on 2025-11-24 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_business_slug'),
        ('reviews', '0003_rename_reviews_re_status_aaaa3f_idx_reviews_rev_status_5966f7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(blank=True, help_text='سوال اول', max_length=500)),
                ('question_2', models.CharField(blank=True, help_text='سوال دوم', max_length=500)),
                ('question_3', models.CharField(blank=True, help_text='سوال سوم', max_length=500)),
                ('question_4', models.CharField(blank=True, help_text='سوال چهارم', max_length=500)),
                ('question_5', models.CharField(blank=True, help_text='سوال پنجم', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_questions', to='loyalty.business')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField(help_text='شماره سوال (1 تا 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating', models.PositiveSmallIntegerField(help_text='امتیاز ستاره (1 تا 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to='loyalty.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to='loyalty.customer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business', 'question_number'], name='reviews_que_busines_f67c8f_idx'), models.Index(fields=['customer'], name='reviews_que_custome_953441_idx')],
                'unique_together': {('business', 'customer', 'question_number')},
            },
        ),
    ]
