# Generated by Django 5.2.7 on 2025-11-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('loyalty', '0005_add_is_reward_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='loyalty.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
