# Generated by Django 5.0.7 on 2025-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(db_index=True, help_text='SHA256 hash of QR payload JSON', max_length=64, unique=True)),
                ('business_id', models.IntegerField(db_index=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('product_ids', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-scanned_at',),
                'indexes': [models.Index(fields=['payload_hash'], name='rewards_qrc_payload_f3ac6f_idx'), models.Index(fields=['business_id', 'scanned_at'], name='rewards_qrc_busines_51a52c_idx')],
            },
        ),
    ]
