# Generated by Django 5.0.7 on 2025-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='scanned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
